version: '2'
services:
    nastava-app:
        image: nastava
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://nastava-postgresql:5432/Nastava
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nastava-postgresql:
        extends:
            file: postgresql.yml
            service: nastava-postgresql
